<a href="https://colab.research.google.com/github/Fais-123/firstRepo/blob/master/Python_Numpy_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")


hello


In [ ]:
print(1)


1


# Python Numpy Library 
Array is a central data structure of the numpy Library. Array contain similar data type elements.


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
type(a)


[1 2 3 4 5]


numpy.ndarray

# Declaring 1D And 2D array

In [ ]:
b=np.array([1,3,5,7,9])
print(b)

#declaring 2D array(2D array is a array of array)
c=np.array([[1,2,5],[1,2,5],[1,2,5]])
print(c)
#What is a vector?
#A vector is a array with a single dimension.(only rows or only columns).

#What is a matrix?
#A matrix is a array with a 2 dimension(means rows and columns).



[1 3 5 7 9]
[[1 2 5]
 [1 2 5]
 [1 2 5]]


In [ ]:
#The numpy ndarray class used to represent both matrices and vectors.
print(type(b))
print(type(c))
#Here e must kno that 1D AND 2D array both types are same which is ndarray.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#For 3D or high dimensions arrays,the term tensor is commonly used.
#TensorFlow is a free and open source software library  for AI AND ML. 
#If anybody is having trouble understanding 3D Matrix (aka Tensor), keep in mind that previously it was referred that Elements inside a Matrix are referred to as i, j, k (alphabetical order); where 'i' is the number of Matrices, 'j' is # of Rows, and 'k' is # of columns. So (2,3,4) means 2 Matrices of 3 Columns and 4 Rows. It is that simple. Cheers!

In [ ]:
#Array Attributes
#1. Dimensions are called Axis.
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#Making 2D array with range 12 and reshape(4,3) it contains 4 rows and 3 columns.
np.arange(12).reshape(4,3)



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.arange(24).reshape(4,6) #Making 2D array with range 24 and reshape(4,6) it contains 4 rows and 6 columns.
  

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
import numpy as np
a=np.arange(48).reshape(6,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]


In [8]:
a.shape

(6, 8)

In [9]:
a.ndim

2

In [10]:
a.itemsize

8

In [11]:
a.size

48

In [20]:
#reshape(4,3,6) means here 4 is no of matrices , 3 is number of rpwa in each matrix and 6 is number of columns in each matrix.
g=np.arange(72).reshape(4,3,6) #Note: product of 4*3*6=72 which is equal to range every range is equal to product of reshape.
print(g)


[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]]

 [[54 55 56 57 58 59]
  [60 61 62 63 64 65]
  [66 67 68 69 70 71]]]


3

In [60]:
g.ndim

g.sum(axis=2) #sum of every matrix row wise


array([[ 15,  51,  87],
       [123, 159, 195],
       [231, 267, 303],
       [339, 375, 411]])

# Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result

In [27]:
x=np.array([10,20,30,40])
y=np.array([0,1,2,3])
z=x-y
print(z)

[10 19 28 37]


In [28]:
z ** 2


array([ 100,  361,  784, 1369])

In [30]:
l=np.array([0,30,60,90])
k=np.sin(l)
print(k)

[ 0.         -0.98803162 -0.30481062  0.89399666]


In [31]:
x

array([10, 20, 30, 40])

In [32]:
y

array([0, 1, 2, 3])

In [33]:
x * y  #elementwise product

array([  0,  20,  60, 120])

In [34]:
x @ y  # matrix product

200

In [36]:
u=np.array([[1,1],[0,1]])
p=np.array([[2,0],[3,4]])
u*p  #elementwise product


array([[2, 0],
       [0, 4]])

In [37]:
u @ p # matrix produc

array([[5, 4],
       [3, 4]])

In [38]:
u.dot(p)  # another matrix product

array([[5, 4],
       [3, 4]])

In [43]:
#linearly spaced arrays
h=np.linspace(0,20,num=6)  #give us 6 num between range to 0 to 20.
h

array([ 0.,  4.,  8., 12., 16., 20.])

In [47]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 4
a

array([[4, 4, 4],
       [4, 4, 4]])

In [50]:
a=rg.random((2,3))
a

array([[0.27496937, 0.65743301, 0.56226566],
       [0.15006226, 0.43263079, 0.6692973 ]])

In [51]:
a.sum()

2.7466583982467023

In [52]:
a.max()

0.6692972985745202

In [53]:
a.min()

0.15006226330533612

In [55]:
t=np.arange(12).reshape(3,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
t.sum(axis=0) #Sum of each column 

array([12, 15, 18, 21])

In [57]:
t.sum(axis=1)  #Sum of each row

array([ 6, 22, 38])

In [61]:
t.cumsum(axis=1)
t# cumulative sum along each row

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
#Plotly is an interactive graphing libraray. in python for plots.
import plotly.express as px
# This dataframe has 244 lines, but 4 distinct values for `day`
df = px.data.tips()
fig = px.pie(df, values='tip', names='day')
fig.show()