<a href="https://colab.research.google.com/github/Fais-123/firstRepo/blob/master/Python_Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")


hello


In [2]:
print(1)


1


# Python Numpy Library 
Array is a central data structure of the numpy Library. Array contain similar data type elements.


In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
type(a)


[1 2 3 4 5]


numpy.ndarray

# Declaring 1D And 2D array

In [9]:
b=np.array([1,3,5,7,9])
print(b)

#declaring 2D array(2D array is a array of array)
c=np.array([[1,2,5],[1,2,5],[1,2,5]])
print(c)
#What is a vector?
#A vector is a array with a single dimension.(only rows or only columns).

#What is a matrix?
#A matrix is a array with a 2 dimension(means rows and columns).



[1 3 5 7 9]
[[1 2 5]
 [1 2 5]
 [1 2 5]]


In [10]:
#The numpy ndarray class used to represent both matrices and vectors.
print(type(b))
print(type(c))
#Here e must kno that 1D AND 2D array both types are same which is ndarray.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#For 3D or high dimensions arrays,the term tensor is commonly used.
#TensorFlow is a free and open source software library  for AI AND ML. 
#If anybody is having trouble understanding 3D Matrix (aka Tensor), keep in mind that previously it was referred that Elements inside a Matrix are referred to as i, j, k (alphabetical order); where 'i' is the number of Matrices, 'j' is # of Rows, and 'k' is # of columns. So (2,3,4) means 2 Matrices of 3 Columns and 4 Rows. It is that simple. Cheers!

In [11]:
#Array Attributes
#1. Dimensions are called Axis.
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones(2)

array([1., 1.])

In [16]:
np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [17]:
np.arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
#Making 2D array with range 12 and reshape(4,3) it contains 4 rows and 3 columns.
np.arange(12).reshape(4,3)



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.arange(24).reshape(4,6) #Making 2D array with range 24 and reshape(4,6) it contains 4 rows and 6 columns.
  

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])