<a href="https://colab.research.google.com/github/Fais-123/firstRepo/blob/master/Python_Numpy_Practice_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Arrays and their Methods/Functions**

In [3]:
import numpy as np
a=np.array([1,6,3,2])
b=np.array([8,9,7,5])
c=np.concatenate((a,b)) #Concatenating two 1D arrays
print(c)

[1 6 3 2 8 9 7 5]


In [4]:
#sorting array
c.sort()
print(c)

[1 2 3 5 6 7 8 9]


# 2D arrays

In [57]:
arr = np.array([1, 2, 3, 4], ndmin=2)
arr

array([[1, 2, 3, 4]])

In [6]:
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[6,9]])  #axis=0 means row wise concatenation
z=np.concatenate((x,y),axis=0) #Concatenating 2D arrays.Dimension must be the same for the concatenation of arrays.
                        #To convert 1D to 2D with dimension 3x2 or 2x3, there should be 6 elements in 1D instead of 7
print(z)

[[1 2]
 [4 5]
 [7 8]
 [6 9]]


In [7]:
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[6,9]])  #axis=1 means column wise concatenation
z=np.concatenate((x,y),axis=1) #Concatenating 2D arrays.Dimension must be the same for the concatenation of arrays.
                        #To convert 1D to 2D with dimension 3x2 or 2x3, there should be 6 elements in 1D instead of 7
print(z)

[[1 2 7 8]
 [4 5 6 9]]


# **3D Arrays OR Tensors**

In [10]:
g=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])  # 3D array is the combination of matrix,rows and columns.
            #here.we have 2 matrices,having 2 rows and 2 columns.
g

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
g.ndim #dimensions of above array or matrix is 3.

3

In [13]:
g.size #size of array is the number of elements in it.

8

In [15]:
g.shape #shape give info about array it contains 2 matrices,2 rows and 2 columns.
#we also use shape to confirm the type of array.

(2, 2, 2)

In [17]:
a=np.arange(9)
print(a)


[0 1 2 3 4 5 6 7 8]


In [18]:
a=a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
np.reshape(a, newshape=(1,9),order='C')
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# **Converting 1D Array into 2D Array**

In [26]:
q=np.array([1,2,3,4,5,6,7,8,9])
q=q.reshape(3,3) #Converting 1D array into 2D array using reshape.
print(q)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
q.ndim


2

In [32]:
h=np.array([1,2,3,4,5,6,7,8,9])
h=h[np.newaxis, : ] #row wise 2d array
print(h)

[[1 2 3 4 5 6 7 8 9]]


In [33]:
h=np.array([1,2,3,4,5,6,7,8,9])
h=h[ :, np.newaxis ] #column wise 2d array
print(h)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# **Slicing In Arrays**

In [40]:
e=np.array([0,1,2,3,4,5,6,7,8,9,10])
e[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
e[3:6] #end element like here 6 it is excusive means not included.

array([3, 4, 5])

In [43]:
e[1:7: 2]
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-6:-1]) #here also in reverse slicing end like here -1 is exclusive(not included).

[2 3 4 5 6]


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5:-2])#here end is -2 so it  is exclusive.

[3 4 5]


In [49]:
a = [0,1, 2, 3, 4, 5, 6, 7, 8]
print(a[0:7:2])

[0, 2, 4, 6]


In [50]:
a = [0,1, 2, 3, 4, 5, 6, 7, 8]
print(a[2:8:3])

[2, 5]


In [51]:
a = [0,1, 2, 3, 4, 5, 6, 7, 8]
print(a[2:-1])    # prints [2,3, 4, 5,6,7]


[2, 3, 4, 5, 6, 7]


In [52]:
a = [1, 2, 3, 4, 5, 6]
print(a[::-1]) 

[6, 5, 4, 3, 2, 1]


# **Slicing 2D Arrays**


In [53]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) #here 1 means 1th index of array and 1:4  means start from index 1  and 4th index is excusive.

[7 8 9]


In [54]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])



[3 8]


In [55]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [62]:
arr = np.array([1, 2, 3, 4], dtype='str')
arr  #STRING TYPE ARRAY

array(['1', '2', '3', '4'], dtype='<U1')

In [65]:
#method to change the data type to integer.
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i') #astype method is use to change data type of array.
print(newarr)


[1 2 3]


In [67]:
#method to make a view of the array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(x)


[1 2 3 4 5]


In [68]:
#syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

(5,)


In [70]:
#NumPy method to change the shape of an array from 1-D to 2-D.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
newarr.ndim

2

In [78]:
#method to change the shape of an array from 2-D to 1-D.


arr = np.array([[1, 2, 3, 4],[8, 9, 10, 11]])

n = arr.reshape(-1)
n


array([ 1,  2,  3,  4,  8,  9, 10, 11])

In [80]:
#method to find all items index with the value 4.

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
x

(array([3, 5, 6]),)